version: '3.7'
services:

  postgres:
    image: postgres:15.6-alpine3.19
    environment:
      POSTGRES_DB: obrio-task-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "NotForProduction"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      obrio-task:

  rabbitmq:
    image: rabbitmq:3.12.12-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    networks:
      obrio-task:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      obrio-task:
networks:
  obrio-task: